/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://ahvhok32rzerhlqlbg3ivyc37e.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zl7uiac5fbhylc32pry2qylv6q",
    "aws_cognito_identity_pool_id": "eu-west-1:9f7be2d4-fc7b-4434-a030-24da6d6cf3c5",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_7fFk2xdIn",
    "aws_user_pools_web_client_id": "70869fb04iqtjv9d0klg43r89s",
    "oauth": {}
};


export default awsmobile;
