/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "http://192.168.0.100:20002/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-fakeApiId123456",
    "aws_appsync_dangerously_connect_to_http_endpoint_for_testing": true,
    "aws_cognito_identity_pool_id": "eu-west-1:9f7be2d4-fc7b-4434-a030-24da6d6cf3c5",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_7fFk2xdIn",
    "aws_user_pools_web_client_id": "70869fb04iqtjv9d0klg43r89s",
    "oauth": {}
};


export default awsmobile;
